# Dependencies
markdown: kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Matthew Hurtado
tagline:          ''
description:      'Student, Tutor, Researcher'
url:              http://hyde.getpoole.com
baseurl:          ''

author:
  name:           Matthew Hurtado
  url:            matthew.e.hurtado@gmail.com

paginate:         5

plugins: 
 - jekyll-paginate

# Custom vars
version:          2.1.0

header_pages:
  - about.md
  - projects.md

github:
  repo:           mehurtado.github.io
